
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gosqladmin
      MYSQL_DATABASE: gosqladmin
      MYSQL_USER: gosqladmin
      MYSQL_PASSWORD: gosqladmin
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - gosqladmin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 7s
      retries: 3

  gosqladmin:
    build:
      context: docker
    depends_on:
      mysql:
        condition: service_healthy
    container_name: gosqladmin
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: debug
      SQL_DRIVER: mysql
      SQL_HOST: mysql
      SQL_PORT: 3306
      SQL_DATABASE: gosqladmin
      SQL_USER: gosqladmin
      SQL_PASSWORD: gosqladmin
      SQL_CONN_TIMEOUT: 60s
      SQL_READ_TIMEOUT: 30s
      SQL_WRITE_TIMEOUT: 30s
      SQL_MAX_OPEN_CONNS: 10
      SQL_MAX_IDLE_CONNS: 5
      SQL_CONN_MAX_LIFETIME: 30m
    volumes:
      - .:/app
    networks:
      - gosqladmin

networks:
  gosqladmin:
    driver: bridge
